[workspace]
authors = ["liar <yyxxyyzero@163.com>"]
channels = ["conda-forge"]
name = "SigWorks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
rich = ">=14.0"
scikit-learn = ">=1.7"

[pypi-dependencies]
torch = { version = ">=2.6", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu124" }
torch_geometric = { version = ">=2.6.0" }
pyg_lib = { url = "https://data.pyg.org/whl/torch-2.6.0%2Bcu124/pyg_lib-0.4.0%2Bpt26cu124-cp312-cp312-win_amd64.whl"}
torch_cluster = { url = "https://data.pyg.org/whl/torch-2.6.0%2Bcu124/torch_cluster-1.6.3%2Bpt26cu124-cp312-cp312-win_amd64.whl" }
torch_scatter = { url = "https://data.pyg.org/whl/torch-2.6.0%2Bcu124/torch_scatter-2.1.2%2Bpt26cu124-cp312-cp312-win_amd64.whl" }
torch_sparse = { url = "https://data.pyg.org/whl/torch-2.6.0%2Bcu124/torch_sparse-0.6.18%2Bpt26cu124-cp312-cp312-win_amd64.whl" }
torch_spline_conv = { url = "https://data.pyg.org/whl/torch-2.6.0%2Bcu124/torch_spline_conv-1.2.2%2Bpt26cu124-cp312-cp312-win_amd64.whl" }